### ISSUE TITLE
When flyweight.py is run as skript it raises an error

### ISSUE THREAD

**Issue by fkromer** [faif/python-patterns#117]
When flyweight.py is run as skript the following output is generated:

```
<Card: 9h> <Card: 9h>
True True
50022776 50022776
True
False
Traceback (most recent call last):
  File "D:\Users\Florian\Documents\GitHub\python-patterns\flyweight.py", line 92, in <module>
    instances_pool = getattr(Card2, 'pool')
AttributeError: type object 'Card2' has no attribute 'pool'
```

**Comment by faif** [comment]
I confirm that it fails in Python 3. Any idea about the source of the problem?

**Comment by fkromer** [comment]
Not yet. I decided to write the unit tests for the other patterns first.

**Comment by ar4s** [comment]
First of all, Python 3 ignores ``__metaclass__`` attribute, use ``class Foo(metaclass=BarMeta)`` for Python 3 or use ``six`` library (https://pythonhosted.org/six/#six.with_metaclass) for cross-version compatibility. Secondly, in Py 3.x ``map`` returns genarator instead of list.

**Comment by faif** [comment]
@ar4s Thanks for the tips. Feel free to fix it if you feel like :)

**Comment by yarikoptic** [comment]
For now I have just "disabled" it in https://github.com/faif/python-patterns/pull/144/commits/393a81f0daa3e55a060015d72f13fa6273ae289a  which is a part of #144 to straighten all the testing

**Comment by faif** [comment]
Hi,

Thanks for your contributions. Sorry for not taking any actions yet but I'm ill. I will check everything after recovering. 

Kind regards,
Sakis

**Comment by duboviy** [comment]
I've added following pull request:
#161 

@faif could you please have a quick look on this issue?

**Comment by faif** [comment]
Although I would prefer to avoid the extra module (six) dependency, it is a solution so thanks @duboviy 👍

**Comment by duboviy** [comment]
Fully agree with @faif that in current project it would be much better to not depend on third party packages.

So if you @faif would like, I'll create a pull request with removing six dependency and using some kind of workaround like this function instead of using six module:

```
def with_metaclass(meta, *bases):
    class metaclass(meta):
        def __new__(cls, name, this_bases, d):
            return meta(name, bases, d)
    return type.__new__(metaclass, 'temporary_class', (), {})

...

class Card2(with_metaclass(FlyweightMeta, object)):

...

```

**Comment by faif** [comment]
@duboviy Sure, go ahead

**Comment by duboviy** [comment]
I've added following pull request:
#162 

@faif, I'm very sorry to disturb you
please, kindly ask you to review this change ;)

**Comment by faif** [comment]
@duboviy Thanks. No need to apologise for your useful contributions 👍
