### ISSUE TITLE
publish_subscribe.py - Method missing?

### ISSUE THREAD

**Issue by fkromer** [faif/python-patterns#127]
The example does not make use of the method Provider.unsubscribe().

I expected that there would be a "wrapping" method like Subscriber.unsubscribe() for removing itself from the Provider (compare: Subscriber.subscribe() for appending itself to the Provider)?

[See draft for publish_subscribe.py tests, line 24](https://github.com/fkromer/python-patterns/blob/test_publish_subscribe/test_publish_subscribe.py)

**Comment by faif** [comment]
Good idea. Feel free to add the `unsubscribe` wrapper to `Subscriber` and I'll merge it

**Comment by fkromer** [comment]
I added the wrapper method and wrote some tests #128

**Comment by faif** [comment]
Thanks :+1:

**Comment by fkromer** [comment]
My pleasure!
