### ISSUE TITLE
Source of these patterns

### ISSUE THREAD

**Issue by harshit298** [faif/python-patterns#134]
Are the concepts portrayed only from GOF's book on design patterns, or is there any other source also used?

**Comment by fkromer** [comment]
Some examples reference an url somewhere in a comment. Many examples are from @faif (aka Sakis Kasampalis in older commits) like proxy.py, just look into the (commit) history of a file. If you are lucky you can get further info about the inital source from the initial commiters...

**Comment by faif** [comment]
@harshit298 The case is as described by @fkromer, so indeed GOF is not by any means the unique reference (although not excluded when relevant)
