### ISSUE TITLE
The get_registry method in registry pattern not work with python2.7

### ISSUE THREAD

**Issue by jxskiss** [faif/python-patterns#149]
The get_registry method defined in RegistryHolder metaclass does not work in BaseRegisteredClass or ClassRegistree.
I tried to define it in class BaseRegisteredClass, and it worked, but I am still confusing about methods defined in metaclass :)<

**Comment by chfw** [comment]
What's more, get_registry() is not used in the example, plus REGISTRY is already a dict why dict(REGISTRY) again. Hence it is redundant.

**Comment by jxskiss** [comment]
@chfw REGISTRY and dict(REGISTRY) is different, by returning REGISTRY directly, it is a reference to the REGISTRY of the root RegistryHolder.REGISTRY, it can be modified, but by returning dict(REGISTRY), a copy of the REGISTRY is generated, you can not modify the root REGISTRY object, it is safe and recommended.
