### ISSUE TITLE
Wrong example for decorator pattern

### ISSUE THREAD

**Issue by pchomik** [faif/python-patterns#150]
Hello,

Based on my materials decorator pattern should be implemented differently. Decorator pattern is not about python decorator or how to change implementation by using python decorator syntax but how to change object's behavior by wrapping it by another.
I found one example for python:  https://wiki.python.org/moin/DecoratorPattern
I don't know if you have access but this is second material (not for python): https://app.pluralsight.com/player?course=patterns-library&author=brian-lagunas&name=decorator&clip=0&mode=live

**Comment by LeMeteore** [comment]
I agree with @pchomik, now what should be done? Write another example? Copy paste the example from wiki.python.org?
