### ISSUE TITLE
Design Pattern Blackboard

### ISSUE THREAD

**Issue by Honzin** [faif/python-patterns#154]
Can you add pattern blackboard? I cannot find this pattern in python on the internet. 
Here is description and Java code.  It would be very usefull make it easier.
https://en.wikipedia.org/wiki/Blackboard_(design_pattern)
Thank you.

P.S. If I add this request on bad place I am very sorry. I am new here.

**Comment by faif** [comment]
Hi,

If you think that the pattern is useful feel free to add an example and I'll approve it.

**Comment by duboviy** [comment]
I've added following pull request:
https://github.com/faif/python-patterns/pull/157

@faif could you please have a quick look on this issue?

**Comment by faif** [comment]
@duboviy Done, thanks 👍
