### ISSUE TITLE
Python Patterns Organization

### ISSUE THREAD

**Issue by fkromer** [faif/python-patterns#158]
Hi @faif, what do you think about to creating a GitHub organization for a central place of python pattern related stuff? I have a lot of python pattern example references to books [here (paste "python" in the search field)](https://eswp3.readthedocs.io/en/master/) which make more sense in a more "python oriented" context. But I think these book references would "waste" your repository. But they would be quite suitable in an organization beside your repository...

**Comment by faif** [comment]
So what would be the purpose of the GitHub organization and how it would like? I'm not familiar with the concept so it would be useful if you can point me to some examples.

**Comment by fkromer** [comment]
There are some [GitHub pages about organizations](https://help.github.com/articles/about-organizations/). In short it is also free, but offers a lot posiblilities to manage maintainenance across organization members and stuff like that. I moved all my "generic pattern language" related repos into some [pattern language organization](https://github.com/pattern-languages) some days ago... just have a look on it.

**Comment by faif** [comment]
In that case it looks like a good idea, since it will be complementary to the repository. If you want to start it go ahead and I'll be happy to link it in the README 👍

**Comment by fkromer** [comment]
Alright. It will take just a few minutes...

**Comment by fkromer** [comment]
Here we go: [Python Pattern Language](https://github.com/python-pattern-language)

I have added you as "owner" organization member. I think you should have [the related priviledges...](https://help.github.com/articles/permission-levels-for-an-organization/)

**Comment by fkromer** [comment]
Because your repo has been forked by other github users it seems that they would have to [adjust their remote paths](https://help.github.com/articles/about-repository-transfers/) if you would add your repo to the organization. Think about it...

**Comment by faif** [comment]
Closing the issue since the organization page is no longer valid
