### ISSUE TITLE
Singleton Pattern

### ISSUE THREAD

**Issue by supritashankar** [faif/python-patterns#163]
I want to create a simple singleton pattern. 

Whose code looks something like this.

    class Singleton(object):
      _instance = None
      def __new__(self):
        if not self._instance:
          self._instance = super(Singleton, self).__new__(self)
          self.num = 10
        return self._instance

    x = Singleton()
    print x.num #10
    x.num = 20
    z = MyClass()
    print z.num #20 

I understand that `Borg` has a singleton class too. But this I felt is a much simpler example. 
If you guys give 👍  I will go ahead and send a PR

cc @faif

**Comment by fkromer** [comment]
Hi @supritashankar, one could consider [some book examples about different singleton variants and implementations](https://github.com/python-pattern-language/python-pattern-references/blob/master/design_patterns/singleton_pattern.rst).

**Comment by supritashankar** [comment]
Thank you @fkromer Closing the issue
