### ISSUE TITLE
repository structure

### ISSUE THREAD

**Issue by bonesmccoy** [faif/python-patterns#165]
Hello,
I found this repository very useful. 
For improve readability it would be nice to structure this repository in modules/ folder (creational, structural).

What do you think about it?

**Comment by fkromer** [comment]
@bonesmccoy When I was setting up some private knowledge management systems (Typo3, etc.) I discovered that a folder structure can not "replace" the funcitonality of tagging/categorization. As patterns can be categorized differently in edition (e.g. [according to the level of abstraction](https://eswp3.readthedocs.io/en/master/design_patterns.html#categorization-of-design-patterns)) I would not recommend that.

**Comment by faif** [comment]
Indeed there are different way of categorising the patterns but following the "intend of optimisation" might be a good idea, since most people are used to that because of the GoF book

**Comment by bonesmccoy** [comment]
The reason behind my suggestion is because here we have a repository aiming to teach design patterns in python by examples and in the README each pattern is under a category so It would be more natural as a learner look for a source of a pattern inside a category-folder name

**Comment by duboviy** [comment]
guys, sorry to disturb, could you please have a quick look on this [pull request](https://github.com/faif/python-patterns/pull/166)?

**Comment by faif** [comment]
Thanks to the work of @duboviy I believe that we have a better structure
