### ISSUE TITLE
__getattr__ usage in some Classes

### ISSUE THREAD

**Issue by coolnay309** [faif/python-patterns#171]
Not so much an issue or a bug, but I noticed that under some __getattr__ usages for eg: https://github.com/faif/python-patterns/blob/master/structural/composite.py#L46 

`if name in self`

But I think it is not necessary. Accessing `self.name` or `getattr(self, 'name')` first checks in `self.__dict__` by default and only then goes into `__getattr__()` for an item that was not in self dict.
Unless I am missing something. Just wanted to drop a note. Great set of examples, btw. Thanks!

**Comment by faif** [comment]
Good proposal. If you have the time go ahead and make the change yourself. You are more than welcome to submit a pull request 👍

**Comment by jefffffrey** [comment]
The example of the composite pattern had been fully replaced, it's time to close the issue.

**Comment by faif** [comment]
@jefffffrey Good point, thanks
