### ISSUE TITLE
The factory method pattern here is actually simple factory pattern

### ISSUE THREAD

**Issue by RoshanPAN** [faif/python-patterns#177]
The factory method pattern here is actually simple factory pattern.

**Comment by faif** [comment]
So, what's the issue here?

**Comment by RoshanPAN** [comment]
In my opinion, Abstract Factory method is used when,  for example, we have several of classes (Dog, Cat, Mouse). Within each class, we have the blue dog, black dog, blue cat, black cat, blue mouse, black mouse.  And also, the blue ones are used together, the black ones are used together.
In this case, using abstract factory would help us to use the "group" inside factory, and get the group of objects together. 

I just read your factory method pattern, it looks like Simple Factory Pattern. 
Being the same as simple factory, Factory method pattern gives us the choice to use a single factory to create different kinds of objects. But the difference is, factory method pattern allowed us to add new products into the factory without changing the factory's code. (To implement this, we need to use reflection.)

Anyway, I think possibly it's because we are using different terminology. I haven't read the GoF yet. Still learning.

**Comment by faif** [comment]
Yes, I think that's a terminology different. Usually the distinction is between the Factory Method (or Simple Factory or just Factory) and the Abstract Factory (group of factories). I'll leave it as is for now.
