### ISSUE TITLE
Short descriptions

### ISSUE THREAD

**Issue by archatas** [faif/python-patterns#184]
It would be useful to have some more detailed descriptions for each pattern. I would put them in the comments above the code. The main questions would be: 

- What the pattern is?
- What the current example does?
- Where can the pattern be used practically (or is used in known open-source projects)?

Some of the patterns have comments or are obvious, but not all of them. Also, I think, that people with different computer science knowledge will check them, so it would be valuable to describe the patterns to them.

**Comment by fkromer** [comment]
I referenced some pattern examples like e.g. [Singleton](https://fkromer.github.io/python-pattern-references/design/#singleton) from different [python-specific books](https://fkromer.github.io/python-pattern-references/bibliography/) in one of my projects. For some embedded software specific patterns I used the common structuring of pattern descriptions (context/when?, problem/why?, forces/what to consider?, solution/how?, example, resulting context/then?) [shortly described here](https://eswp3.readthedocs.io/en/master/about.html#why-principles-pattern-languages-and-patterns) in another project. This works pretty well but the "descriptions" of single patterns tend to become very huge (especially if you consider programming language specific implementation variants/alternatives and/or context specific variants of the patterns) means very time consuming. Currently I try to stick to short listings of just kewords or one-liners which e.g. do just state but not explain the backgrounds right there but reference the reasoning from second sources (preferably "ever-green" books). However this requires that one already has some background...

**Comment by faif** [comment]
I find the reference of @fkromer a good start. @archatas do you think adding links to his examples suffices?

**Comment by archatas** [comment]
Yes, these seem quite helpful: https://fkromer.github.io/python-pattern-references/design/

**Comment by faif** [comment]
Good. Feel free to do it if you want and I'll merge it happily :)

**Comment by archatas** [comment]
Good idea :)
I just have to finish some project I am working on at first.

**Comment by faif** [comment]
@mshcruz Started working on that and he is welcoming suggestions. Feel free to give them 👍
