### ISSUE TITLE
Design for Testability Patterns

### ISSUE THREAD

**Issue by fkromer** [faif/python-patterns#185]
I would like to port the "Design for Testability" pattern examples from [xUnit Test Patterns: Refactoring Test Code](https://www.amazon.com/xUnit-Test-Patterns-Refactoring-Code/dp/0131495054) (the patterns of this category are actually no test code but production code patterns) which are in Java and VB to Python. Anyone interested in joining...

Short and eventually outdated descriptions of the patterns can be found [here](http://xunitpatterns.com/DfT%20Patterns.html):

- Dependency Injection
  - Parameter Injection (implementation variant) :heavy_check_mark:
  - Constructor Injection (implementation variant) :heavy_check_mark:
  - Setter Injection (implementation variant) :heavy_check_mark:
- Dependency Lookup
- Humble Object
  - Poor Man's Humble Object (implementation variant)
  - True Humble Object (implementation variant)
  - Subclassed Humble Object (implementation variant)
  - Humble Dialog (context variant)
  - Humble Executable (context variant)
  - Humble Transaction Controller (context variant)
  - Humble Container Adapter (context variant)
- Test Hook
  - System Under Test Hook (implementation variant)
  - Depended-on Component Hook (implementation variant)

**Comment by fkromer** [comment]
[pull request "constructor injection"](https://github.com/faif/python-patterns/pull/186)

**Comment by faif** [comment]
Effort already started and merged thus closing the issue
