### ISSUE TITLE
Unicode and Python-3 compatibility

### ISSUE THREAD

**Issue by krmanish** [faif/python-patterns#217]
I think we should use Python-3 compatible code for unicode. 

> from __future__ import unicode_literals 

Found [here](https://github.com/faif/python-patterns/blob/master/creational/lazy_evaluation.py#L76) and and all other places wherever required.

**Comment by faif** [comment]
@krmanish I agree. Those u should go away :)

**Comment by faif** [comment]
@sara-02 Good point, closing this ticket in favor of #208
