### ISSUE TITLE
Singleton example

### ISSUE THREAD

**Issue by GeorgiosGoniotakis** [faif/python-patterns#226]
Hello there. I noticed that there is no example of the Singleton design pattern. However, I saw an example of Borg https://github.com/faif/python-patterns/blob/master/creational/borg.py I was thinking of adding that. Any thoughts?

**Comment by fkromer** [comment]
I collected some references to implementation variants of the singleton pattern in Python some while ago: [python-pattern-reference - singleton pattern](https://fkromer.github.io/python-pattern-references/design/#singleton). In the meanwhile new books came out which could come with new, different implementations (I am quite sure about it but I had no time to look into it in detail so far).

**Comment by faif** [comment]
@GeorgiosGoniotakis In Python there two recommended ways of implementing a singleton:

- Use a module (by definition can only be imported onced)
- Use borg

Since those singleton implementations are considered more of an antipattern I've resisted adding them
