### ISSUE TITLE
Why are TL;DR suffixed with 80?

### ISSUE THREAD

**Issue by foxyblue** [faif/python-patterns#228]
[I have just continued as per the other examples](https://github.com/faif/python-patterns/blob/master/behavioral/chain.py#L18), but I don't know why?

**Comment by gyermolenko** [comment]
I see no other explanation.
Maybe the mystery (and this issue) is resolved? :)

**Comment by ammarnajjar** [comment]
I bumped into this Issue by chance, I allowed myself to drop some thoughts as well.
This question is probably relates to #213 where `*TL;DR80` is added in most comment sections.

I could understand the TLDR part, but the 80 part I also could not understand.
I would suggest closing this issue by answering that unless @foxyblue has something against that :-)

**Comment by foxyblue** [comment]
I think we have come to some understanding that it has to do with an 80-character code line limit, but for this indication, to be stated after TL;DR, I have found no convention or practice that holds us against removing it.

For a line length of 80 to be stated in every file and not enforced by a linter seems archaic.

I'd like to turn this issue into a task which is resolved by removing all "80" suffixes and replace with a line length check.

**Comment by faif** [comment]
@foxyblue Please go ahead and do it. I agree with the proposal and generally the 80-character limit is not very useful for the modern monitors.
