### ISSUE TITLE
[question]should the borg design pattern override __deepcopy__() ? 

### ISSUE THREAD

**Issue by sak96** [faif/python-patterns#239]
- borg as i see it is equivalent of singleton for python
- but it does not handle deepcopy very well
- shouldn't there be a \_\_deepcopy\_\_ method?
- correct me if i am wrong

**Comment by gyermolenko** [comment]
hi @sak96 
You are correct in notion that Borg does not handle deepcopy very well. Neither it does for shallow copy (`copy.copy(..)`). 
But I don't think its his responsibility.
1. "the singleton pattern is a software design pattern that restricts the **instantiation** of a class to one." ([link](https://en.wikipedia.org/wiki/Singleton_pattern))
2. You can work around that: `In order for a class to define its own copy implementation, it can define special methods __copy__() and __deepcopy__(). ` ([link](https://docs.python.org/3.7/library/copy.html))

So I would say "not a bug". What do you think?

**Comment by sak96** [comment]
yes. I agree. 
After reading more about data structure I would say sometime deep copy or copy may not be necessary. it is more to understand the essence of the pattern. back then when I had just started I felt that this was something which was worth thinking about. but now I look back and feel that most of the time you have to tweak a little bit for a pattern to be helpful.
Any how thanks for resolving my query.

**Comment by gyermolenko** [comment]
great!
"but now I look back and feel that most of the time you have to tweak a little bit for a pattern to be helpful" - well said. Fits my experience as well.
