### ISSUE TITLE
Simplification of structural/mvc.py

### ISSUE THREAD

**Issue by tomschr** [faif/python-patterns#247]
The code from [structural/mvc.py](https://github.com/faif/python-patterns/blob/master/structural/mvc.py#L29-L36) can be replaced by a more concise and simpler version:

```python
class Price1(float):
    def __str__(self):
        return "{:.2f}".format(self)
```

**Comment by faif** [comment]
Hi,

Thanks for the suggestion. Feel free to submit a pull request and I happily approve it.
