### ISSUE TITLE
Move from nose to pytest for testing

### ISSUE THREAD

**Issue by gyermolenko** [faif/python-patterns#259]
**Motivation:**
- `pytest` is stable, extensible, popular etc etc
- last `nose` release was on Jun 2, 2015

**Notes:**
- `pytest` runs `unittest.TestCase` wo modifications
- `pytest` is also available in travis env by default

@faif (or other maintainers) what do you think?

**Comment by faif** [comment]
I think that it's a good idea. I like `pytest` and it seems that this is the current goto platform for unit testing in Python
