### ISSUE TITLE
Corrupted git file history

### ISSUE THREAD

**Issue by fkromer** [faif/python-patterns#298]
I am looking for a new employment right now and thought about letting people know about my contributions in this repository. Unfortunately this [PR](https://github.com/faif/python-patterns/commit/2e1f57c95cb1124bbe7a736b265343db3716a05b) corrupted the git file history. The project's contribution overview does not show contributions correctly anymore and it's also not possible to get the information with `git log`. It would be great if someone could fix that. This [gist about how to move files without loosing the file history](https://gist.github.com/ajaegers/2a8d8cbf51e49bcb17d5) could be a starting point.

**Comment by gyermolenko** [comment]
hi @fkromer , sorry to hear that my PR created inconveniences for someone. 
It was tracked as `git rename` action, which is not a crime by my book.

Can you please try `git log --follow <filename>` command?
E.g. `git log --follow patterns/behavioral/catalog.py` shows history before catalog structure has changed.

**Comment by fkromer** [comment]
@gyermolenko Thanks for this super fast response. Using `git log` on files like e.g. `git log --follow patterns/other/hsm/hsm.py` works. However my hope was that it is possible to restore the log information on the publicly accessible project site and in my account's contribution activites somehow. Good to know that GitHub's user contribution statistics are that unreliable. The unofficial ticket for native support got another thumbs up :)

**Comment by gyermolenko** [comment]
I've just checked, and if you copy repo from github to gitlab - their file history follows git renames.
As an option - to put gitlab link with disclaimer into resume so it can be used simply like `alternative git web ui with more representative file history`

**Comment by fkromer** [comment]
The GitHub [repo pull mirrored into GitLab](https://gitlab.com/fkromer/python-patterns) displays [project contributions](https://gitlab.com/fkromer/python-patterns/graphs/master) and [git file historys](https://gitlab.com/fkromer/python-patterns/commits/master/patterns/other/hsm/hsm.py) correctly.
