### ISSUE TITLE
Gradually add type hints to the examples

### ISSUE THREAD

**Issue by rednafi** [faif/python-patterns#325]
A few examples (like the **_delegation_** pattern) can be difficult to understand without **_type hints_**. Unless you want to keep backward compatibility with older Python versions, adding type hints can make the intents of the code snippets clearer.

**Comment by faif** [comment]
That is a good suggestion. Backward compatibility is not extremely useful, since Python 2.x has reached EOL

**Comment by rednafi** [comment]
Yeah, since you can add the type hints gradually, it shouldn't be problem to convert. I've already added type checking to the delegation pattern and sent a PR.

**Comment by fkromer** [comment]
> That is a good suggestion. Backward compatibility is not extremely useful, since Python 2.x has reached EOL

"Le roi est mort, vive le roi" :wink:

**Comment by faif** [comment]
Closing it since the effort has already started. Thanks @rednafi
