### ISSUE TITLE
[question]Is the example of abstract factory pattern too simple?

### ISSUE THREAD

**Issue by cyan-T** [faif/python-patterns#366]
In my opinion, abstract factory serves to provide a series of objects, but in the example it just provides one product, which looks like factory method pattern. Is my understanding wrong?

**Comment by faif** [comment]
Abstract factory doesn't have to provide a series of objects, but it can use more than one factories to create different types of objects that makes sense to group. Feel free to provide a more elaborate example if you think that it will make things more clear.

**Comment by cyan-T** [comment]
Thanks.
