### ISSUE TITLE
observer.py imports typing.Protocol which is not in Python 3.7

### ISSUE THREAD

**Issue by yhay81** [faif/python-patterns#369]
I got an error when I run `tox`
E   ImportError: cannot import name 'Protocol' from 'typing' (/Users/yhay81/.pyenv/versions/3.7.9/lib/python3.7/typing.py)

It is because observer.py import typing.Progocol and typing.Progocol is new in Python version 3.8.
https://docs.python.org/3/library/typing.html#typing.Protocol
(It is from #345)

I think this is one of a solution.
- Drop testing 3.7 in tox.
- Write notation comment in observer.py which says it is new feature of 3.8

I can make PR if this is okay.

**Comment by yhay81** [comment]
I dropped testing 3.7 in tox: #372
If it is okay that this repo do not support 3.7, I think this issue can be closed.

**Comment by faif** [comment]
Yeah, that's fine. In general it's good to keep up with the latest minor version + 1 or more minor older versions, but we don't need to support all of them.
