### ISSUE TITLE
No return value expected

### ISSUE THREAD

**Issue by g-paras** [faif/python-patterns#377]
https://github.com/faif/python-patterns/blob/5f47b07dbf2867b0b35866301573439b4e8e37ae/patterns/creational/prototype.py#L32-L38

According to type hint None type should be returned but obj of type `Prototype` is returned.

**Comment by faif** [comment]
You are right, that was introduced in https://github.com/faif/python-patterns/commit/a12ad8e7dc00572ba09bcacddb4862cc8cbdba4d#diff-292e21ea71bfaa9c4ecf149a183f5080c973cf7b22bb080b7b520e5875476c0dR29. Feel free to submit a fix
