### ISSUE TITLE
what's the difference betwen builder.py and abstruct_factory.py

### ISSUE THREAD

**Issue by loveJasmine** [faif/python-patterns#384]

**Comment by faif** [comment]
They are two different ways of creating objects. A builder typically creates a complex object in multiple steps, and until the final `build`/`create` function is executed the object is incomplete

**Comment by loveJasmine** [comment]
@faif  Thanks

Maybe you can write a little more like what's the difference btw those pattern, and where and how to utilize it in different scnerio
