### ISSUE TITLE
Shortened URL is spam now

### ISSUE THREAD

**Issue by rachtsingh** [faif/python-patterns#390]
https://github.com/faif/python-patterns/blob/79d12755010a33a5195d5475a2c8853cda674c29/patterns/creational/factory.py#L15

Just wanted to point out that this link is now spam which tries to fire a WhatsApp message on your behalf... I'm assuming this is the URL shortening company up to some hijinks? Google recommends Bit.ly or Ow.ly as alternatives to their previous goo.gl.

**Comment by faif** [comment]
Thanks for pointing this out. That sucks. I'll remove it right away.

**Comment by faif** [comment]
Fixed in 0a15bbe459d198d37bba648d8752ad75f1ed0c5d
