### ISSUE TITLE
Add Protocol to factory pattern

### ISSUE THREAD

**Issue by mfurquimdev** [faif/python-patterns#402]
Hi 👋🏽 

I see we have some type hints that's been continuously added as mentioned at #373.

As the factory pattern has the constrain of both classes having to implement a `localize` method, I thought it might be a good idea to reinforce this constrain by using Protocol.

I'd gladly implement this if it's okay.

Here's the [PEP-0544](https://peps.python.org/pep-0544/) and the [Python docs](https://docs.python.org/3/library/typing.html#typing.Protocol) for Protocols.

**Comment by faif** [comment]
Hi,

Sure, go ahead.
