### ISSUE TITLE
[Question] Why using `Type[Localizer]` instead `Localizer`?

### ISSUE THREAD

**Issue by working12** [faif/python-patterns#406]
https://github.com/faif/python-patterns/blob/d4b7f97b3ac07cb545caca32826186e32ec1d88a/patterns/creational/factory.py#L55

In this code, why are we using `Type[Localizer]` instead of just using `Localizer`?

**Comment by DKorytkin** [comment]
for using `Localizer` instead of  `Type[Localizer]` 
values of this dict must be instances
