### ISSUE TITLE
Paper Identification

### ISSUE THREAD

**Issue by eliotest98** [faif/python-patterns#411]
Hello I am a researcher in a particular field that for copyright reasons I cannot explain. Since I am writing a paper and would like to use this repository for my purpose I would like to know if there is an official source (a paper) that talks about the construction of this repository or even just how it was conceived.

**Comment by eliotest98** [comment]
Hello and thank you for your response first of all. This information you have given me is already in my possession (what I am doing is really based on Gang of Four). What I would like to understand is something more historical like why it was created and on what basis it was created. All in the form of a paper. It does not need to have all of the above information the important thing basically is that there is an official source that talks about even one of these things. My goal is to cite this paper and reference this repository. But unfortunately in academia without a paper it is not possible to cite. I have also tried searching and found only papers that use it without citing it. And that is why I am here

**Comment by faif** [comment]
Hi,

I'm the repo creator and I can assure you that there's no official paper behind it. It was created to have something more organised and under version control, instead of looking for random Internet resources. There is a whole discussion about copyright issues in #143 because some files are actual copies as found on the Internet, but that it's hard to resolve since we can't track everything and the original creators had no copyright assigned.

**Comment by eliotest98** [comment]
> Hi,
> 
> I'm the repo creator and I can assure you that there's no official paper behind it. It was created to have something more organised and under version control, instead of looking for random Internet resources. There is a whole discussion about copyright issues in #143 because some files are actual copies as found on the Internet, but that's hard to resolve since we can't track everything and the original creators had no copyright assigned.

Hi I thank you for your time as it is not for everyone. I really understand and regret it as it is very well structured and can be used in literature for different purposes. I thank you anyway and if I have any other questions I will not hesitate to get back to you via this thread.

**Comment by eliotest98** [comment]
@grimley517 yes, the root cause is the citability of this project. Based on what I was told it is necessary to have an academic source to cite repositories. The solution you propose I'm not sure is the correct way to go (I've seen it too and will discuss it with those in charge shortly). But even if it were a viable route, though, there could still be problems in that you have to have a license in the repository, and from what I understand, one of the main problems relates to that. In any case i discuss with those in charge the next week and i will update you in case.

**Comment by grimley517** [comment]
For the license you would definitely need to consult @faif. This is his repo.

**Comment by eliotest98** [comment]
Hello, sorry for the long delay. I spoke with the people in charge and they told me that copyrigth issues should be fixed and that it is possible to cite you even with just the link to the github repository.I have nothing more to ask or report to you. Unfortunately, I have no way, at least for now, to be able to cite you. In case you solve the problem before the end of my work I would be delighted to be able to cite you. If you want to keep the question open for memo otherwise you can also close the discussion. Thanks for all.

**Comment by faif** [comment]
Good luck with your report. I’ll close this issue since there is nothing more to be said.
