### ISSUE TITLE
Add classifications of patterns so it's easy to find necessary one

### ISSUE THREAD

**Issue by polusok** [faif/python-patterns#70]
Creational patterns
Structural patterns
Behavioral patterns
Concurrency patterns

**Comment by faif** [comment]
Thanks for the suggestion. Where do you suggest to do that? Feel free to change it in README.md or create directories and move the relevant patterns inside and I'll approve it :)

**Comment by gzog** [comment]
That would be really helpful yeah!

**Comment by BurningPixel** [comment]
How would you classify the patterns, in the file names or with folders?

**Comment by faif** [comment]
I find both approaches fine.

**Comment by LiVincent-Zhang** [comment]
I think it is a good idea that add the classification just in *README.md* .

**Comment by faif** [comment]
@LiVincent-Zhang Feel free to commit a change :)

**Comment by FalloutX** [comment]
@faif this is still not done. I'll try to do this. I'll just update the classfication in the the README.md.

**Comment by faif** [comment]
@FalloutX Great, thanks :+1:
