### ISSUE TITLE
Another pattern for lazy evaluation

### ISSUE THREAD

**Issue by kissgyorgy** [faif/python-patterns#88]
There is another pattern for the lazy evaluation https://github.com/faif/python-patterns/blob/master/lazy_evaluation.py
called cached_property. It does almost the same as lazy_evaluation.py, but instead of setting a different name on the object dict, it sets the same name, so the actual property will be shadowed (but not lost).
Invalidating the cached value is by simply deleting it.
You can read more about it here: http://www.pydanny.com/cached-property.html

**Comment by maximilianr** [comment]
I think that's the same as the lazy library (https://pypi.python.org/pypi/lazy), and does seem like a better design, even if you have to understand a bit more about how python looks up instance & class attributes.

**Comment by faif** [comment]
@kissgyorgy @maximilianr Thanks for the info. The main idea is the same in all cases. A generic decorator-based solution. I'm not sure if it's worthwhile to add another example or replace the existing.

**Comment by karlicoss** [comment]
btw the stdlib has `cached_property` from 3.8, perhaps worth mention https://docs.python.org/3/library/functools.html#functools.cached_property
