### ISSUE TITLE
Calling business logic on different physical machine

### ISSUE THREAD

**Issue by heshamfm** [faif/python-patterns#90]
In 3-tier.py the UI class makes a normal call to the business logic class as if they both run on the same machine, rather it must cater for calling business logic that resides on a centralized separate machine. I hope I'm not missing the point.

**Comment by faif** [comment]
Correct, but how could you implement that as an example? It's more convenient to demonstrate it by placing all tiers in the same machine.

**Comment by heshamfm** [comment]
For demo purpose,  yes, absolutely agree
